
[fdd_config]
fields = [
    {name = 'SrcIP', type = 'DirSet'},
    {name = 'DstIP', type = 'DirSet'},
    {name = 'Protocol', type = 'ProtSet'},
    {name = 'SrcPort', type = 'PortSet'},
    {name = 'DstPort', type = 'PortSet'}
]