name: Python CI

on:
  push:
    branches:
        - ci_workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Generate default_reqs.txt from pyproject.toml
      run: |
        mkdir -p requirements
        pip-compile --extra=test --output-file=requirements/default_reqs.txt --generate-hashes pyproject.toml

    - name: Install dependencies
      run: |
        pip install -r requirements/default_reqs.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest
