name: Python CI

on:
  push:
    branches:
      - ci_workflow

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Generate default_reqs.txt from pyproject.toml
      run: |
        mkdir -p requirements
        pip-compile --extra=test --output-file=requirements/default_reqs.txt --generate-hashes pyproject.toml

    - name: Install dependencies
      run: |
        pip install -r requirements/default_reqs.txt

    - name: Lint with PyLint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest --disable-warnings
